### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by Doc-T-or** [OSINT-mindset/osint-mindset-org-ru#5]
Links [OSINT RU events](https://t.me/osint_ru_events) and [OSINT RU events](https://t.me/osint_ru_events) do not work in [Что почитать](https://github.com/OSINT-mindset/osint-mindset-org-ru/blob/main/community/kogo-pochitat.md)

**Comment by soxoj** [comment]
Thank you. This channel was closed

**Comment by soxoj** [comment]
Fixed in [b6c39c4](https://github.com/OSINT-mindset/osint-mindset-org-ru/commit/b6c39c42a2e89f38d6e54d176be42f4a2d6a15b5)
